#!/usr/bin/env python3
"""
================================================================================
 BITS Pilani - WILP - MTech (AI & ML)
 S2_2025-2026, AIMLCZG557 / AECLZG557 - Applied Concepts in AI
 Assignment 2 - PS04 : Hex Game AI using Monte Carlo Tree Search (MCTS/UCT)
 Group ID : G116
================================================================================

 PROBLEM
 -------
 Play the game of Hex on an N x N board (7 <= N <= 11).
   * Player A  -> symbol 1 -> AI agent    -> must connect TOP row to BOTTOM row.
   * Player B  -> symbol 2 -> Human       -> must connect LEFT col to RIGHT col.
   * Player A (AI) always makes the first move.

 The AI agent selects its move with Monte Carlo Tree Search driven by the
 Upper Confidence Bound for Trees (UCT) policy and implements the four
 canonical phases:
       1. Selection      (UCT tree policy)
       2. Expansion      (add one untried child)
       3. Simulation     (uniformly random rollout to a terminal state)
       4. Backpropagation(update visit / win statistics up the path)

 HEX ADJACENCY (square-matrix encoding of the hexagonal grid)
 -----------------------------------------------------------
       Orthogonal        : (r-1,c) (r+1,c) (r,c-1) (r,c+1)
       Allowed diagonals : (r-1,c+1) [Top-Right] , (r+1,c-1) [Bottom-Left]
       Forbidden         : (r-1,c-1) [Top-Left]  , (r+1,c+1) [Bottom-Right]

 FILES
 -----
       inputPS04.txt   : line 1 -> board size N
                         line 2 -> time limit per AI move in milliseconds
                         next N lines -> the N x N board matrix (0/1/2)
       outputPS04.txt  : complete transcript of the game (generated by this run)

 USAGE
 -----
       python G116_A2_PS04.py                  # play the game (interactive)
       python G116_A2_PS04.py --test           # run the built-in test cases
       python G116_A2_PS04.py --input in.txt --output out.txt
================================================================================
"""

import argparse
import math
import os
import random
import re
import sys
import time

# ----------------------------------------------------------------------------
# Global constants
# ----------------------------------------------------------------------------
EMPTY = 0
PLAYER_A = 1                      # AI agent      : TOP  -> BOTTOM
PLAYER_B = 2                      # Human player  : LEFT -> RIGHT

PLAYER_NAME = {PLAYER_A: "A", PLAYER_B: "B"}

MIN_BOARD_SIZE = 7
MAX_BOARD_SIZE = 11

DEFAULT_INPUT_FILE = "inputPS04.txt"
DEFAULT_OUTPUT_FILE = "outputPS04.txt"
DEFAULT_TIME_LIMIT_MS = 2000

# The six legal neighbours of a cell (dr, dc) - see adjacency rules above.
NEIGHBOUR_OFFSETS = ((-1, 0), (1, 0), (0, -1), (0, 1), (-1, 1), (1, -1))

# UCT exploration constant.  c = sqrt(2) is the theoretical value for rewards
# normalised to [0, 1], which is exactly our win / loss reward scheme.
EXPLORATION_CONSTANT = math.sqrt(2)

SEPARATOR = "=" * 78


# ----------------------------------------------------------------------------
# Exceptions - every data-structure operation raises a descriptive message
# ----------------------------------------------------------------------------
class HexError(Exception):
    """Base class for every error raised by this program."""


class InvalidBoardError(HexError):
    """Raised when the board specification / input file is malformed."""


class InvalidMoveError(HexError):
    """Raised when a move is syntactically or semantically illegal."""


class BoardFullError(HexError):
    """Raised when an insert is attempted on a board with no empty cell."""


class EmptyTreeError(HexError):
    """Raised when the search tree has no child to select from."""


# ============================================================================
# 1. GAME MODEL
# ============================================================================
class HexBoard:
    """
    The Hex board.

    The N x N matrix is stored as a *flat* python list of length N*N so that a
    cell can be addressed by a single integer index (index = row * N + col).
    A flat list makes the millions of read/copy operations performed during the
    MCTS rollouts noticeably cheaper than a list-of-lists.

    The neighbour table is pre-computed once per board size and shared by every
    copy of the board, so adjacency look-up during a rollout costs O(1).
    """

    __slots__ = ("size", "cells", "neighbours")

    def __init__(self, size, cells=None, neighbours=None):
        if not isinstance(size, int) or size < 2:
            raise InvalidBoardError(
                "Board size must be an integer >= 2 (received: %r)." % (size,))
        self.size = size
        if cells is None:
            self.cells = [EMPTY] * (size * size)
        else:
            if len(cells) != size * size:
                raise InvalidBoardError(
                    "Board data holds %d cells but %d were expected for a "
                    "%dx%d board." % (len(cells), size * size, size, size))
            self.cells = list(cells)
        self.neighbours = neighbours if neighbours is not None \
            else self._build_neighbour_table(size)

    # -- construction helpers -------------------------------------------------
    @staticmethod
    def _build_neighbour_table(size):
        """Pre-compute, for every flat index, the tuple of its legal neighbours."""
        table = []
        for r in range(size):
            for c in range(size):
                nb = []
                for dr, dc in NEIGHBOUR_OFFSETS:
                    nr, nc = r + dr, c + dc
                    if 0 <= nr < size and 0 <= nc < size:
                        nb.append(nr * size + nc)
                table.append(tuple(nb))
        return table

    def copy(self):
        """Fast clone - the immutable neighbour table is shared, not copied."""
        return HexBoard(self.size, self.cells, self.neighbours)

    # -- coordinate helpers ---------------------------------------------------
    def index(self, row, col):
        return row * self.size + col

    def coords(self, idx):
        return divmod(idx, self.size)

    def neighbours_of(self, row, col):
        """Public helper returning the (row, col) neighbours of a cell."""
        if not self.in_bounds(row, col):
            raise InvalidMoveError("Cell (%d,%d) is outside the board." % (row, col))
        return [self.coords(i) for i in self.neighbours[self.index(row, col)]]

    def in_bounds(self, row, col):
        return 0 <= row < self.size and 0 <= col < self.size

    # -- insert / delete ------------------------------------------------------
    def legal_moves(self):
        """All empty cells, as flat indices."""
        return [i for i, v in enumerate(self.cells) if v == EMPTY]

    def is_full(self):
        return EMPTY not in self.cells

    def place(self, idx, player):
        """INSERT operation: put `player`'s stone on the empty cell `idx`."""
        if not 0 <= idx < len(self.cells):
            raise InvalidMoveError("Move index %r is outside the board." % (idx,))
        if self.cells[idx] != EMPTY:
            r, c = self.coords(idx)
            raise InvalidMoveError(
                "Cell (%d,%d) is already occupied by Player %s."
                % (r, c, PLAYER_NAME[self.cells[idx]]))
        self.cells[idx] = player

    def remove(self, idx):
        """DELETE operation: undo a stone placement (used by the tactical scan)."""
        if not 0 <= idx < len(self.cells):
            raise InvalidMoveError("Move index %r is outside the board." % (idx,))
        if self.cells[idx] == EMPTY:
            r, c = self.coords(idx)
            raise InvalidMoveError(
                "Cannot remove from cell (%d,%d): the cell is already empty." % (r, c))
        self.cells[idx] = EMPTY

    def validate_move(self, row, col):
        """Validate a human move and return its flat index."""
        if not self.in_bounds(row, col):
            raise InvalidMoveError(
                "Move (%d,%d) is out of range - valid rows/cols are 0..%d."
                % (row, col, self.size - 1))
        idx = self.index(row, col)
        if self.cells[idx] != EMPTY:
            raise InvalidMoveError(
                "Cell (%d,%d) is already occupied by Player %s."
                % (row, col, PLAYER_NAME[self.cells[idx]]))
        if self.is_full():
            raise BoardFullError("The board is full - no further moves are possible.")
        return idx

    # -- terminal test --------------------------------------------------------
    def _edge_cells(self, player):
        """Source cells (start edge) and the goal-edge predicate for `player`."""
        n = self.size
        if player == PLAYER_A:                       # top row -> bottom row
            sources = [c for c in range(n) if self.cells[c] == PLAYER_A]
            goal = lambda i: i >= n * (n - 1)        # noqa: E731
        else:                                        # left col -> right col
            sources = [r * n for r in range(n) if self.cells[r * n] == PLAYER_B]
            goal = lambda i: i % n == n - 1          # noqa: E731
        return sources, goal

    def is_connected(self, player):
        """True when `player` has completed a chain between his two edges."""
        sources, goal = self._edge_cells(player)
        if not sources:
            return False
        seen = bytearray(len(self.cells))
        stack = []
        for i in sources:
            seen[i] = 1
            stack.append(i)
        cells, nbrs = self.cells, self.neighbours
        while stack:
            i = stack.pop()
            if goal(i):
                return True
            for j in nbrs[i]:
                if cells[j] == player and not seen[j]:
                    seen[j] = 1
                    stack.append(j)
        return False

    def winner(self):
        """Return 1 / 2 for a winner, 0 when the game is still running."""
        if self.is_connected(PLAYER_A):
            return PLAYER_A
        if self.is_connected(PLAYER_B):
            return PLAYER_B
        return EMPTY

    def winning_path(self, player):
        """
        Shortest winning chain of `player` as a list of (row, col) tuples.
        Breadth-first search guarantees the shortest connecting path.
        """
        sources, goal = self._edge_cells(player)
        if not sources:
            return []
        parent = {}
        queue = []
        for i in sources:
            parent[i] = None
            queue.append(i)
        cells, nbrs = self.cells, self.neighbours
        head = 0
        while head < len(queue):
            i = queue[head]
            head += 1
            if goal(i):
                path = []
                while i is not None:
                    path.append(self.coords(i))
                    i = parent[i]
                return list(reversed(path))
            for j in nbrs[i]:
                if cells[j] == player and j not in parent:
                    parent[j] = i
                    queue.append(j)
        return []

    # -- presentation ---------------------------------------------------------
    def render(self):
        """Plain matrix rendering, exactly as used by the input file."""
        n = self.size
        return "\n".join(" ".join(str(self.cells[r * n + c]) for c in range(n))
                         for r in range(n))

    def stone_count(self, player):
        return self.cells.count(player)


def player_a_wins_on_full_board(cells, size, neighbours):
    """
    Fast terminal test used by the rollouts.

    A completely filled Hex board always has exactly one winner (no draws), so
    it is enough to test Player A's top-bottom connection: if A is not
    connected then B necessarily is.  Implemented as an iterative depth-first
    flood fill over a bytearray (no recursion, no set hashing) because this is
    the single hottest function of the whole program.
    """
    stack = [c for c in range(size) if cells[c] == PLAYER_A]
    if not stack:
        return False
    seen = bytearray(size * size)
    for i in stack:
        seen[i] = 1
    last_row_start = size * (size - 1)
    while stack:
        i = stack.pop()
        if i >= last_row_start:
            return True
        for j in neighbours[i]:
            if cells[j] == PLAYER_A and not seen[j]:
                seen[j] = 1
                stack.append(j)
    return False


# ============================================================================
# 2. MONTE CARLO TREE SEARCH
# ============================================================================
class MCTSNode:
    """
    One node of the Monte Carlo search tree.

    `player_just_moved` is the player who created this node's position, so the
    node's win counter is maintained from *that* player's point of view - this
    is what makes the UCT value directly comparable between siblings.
    """

    __slots__ = ("move", "parent", "children", "untried_moves",
                 "visits", "wins", "player_just_moved", "terminal_winner")

    def __init__(self, move, parent, player_just_moved, untried_moves):
        self.move = move
        self.parent = parent
        self.children = []
        self.untried_moves = untried_moves
        self.visits = 0
        self.wins = 0.0
        self.player_just_moved = player_just_moved
        self.terminal_winner = EMPTY      # != 0 -> this position ends the game

    # -- 1. SELECTION ---------------------------------------------------------
    def uct_select_child(self, exploration=EXPLORATION_CONSTANT):
        """Return the child maximising  w/n + c * sqrt(ln(N) / n)."""
        if not self.children:
            raise EmptyTreeError(
                "Selection failed: node has no children to select from.")
        log_parent = math.log(self.visits) if self.visits > 0 else 0.0
        best, best_score = None, -1.0
        for child in self.children:
            score = (child.wins / child.visits
                     + exploration * math.sqrt(log_parent / child.visits))
            if score > best_score:
                best, best_score = child, score
        return best

    # -- 2. EXPANSION ---------------------------------------------------------
    def expand(self, move, player):
        """Attach a new child produced by `player` playing `move`."""
        if self.untried_moves and move in self.untried_moves:
            self.untried_moves.remove(move)
        child = MCTSNode(move, self, player, None)
        self.children.append(child)
        return child

    # -- 4. BACKPROPAGATION ---------------------------------------------------
    def update(self, winner):
        self.visits += 1
        if winner == self.player_just_moved:
            self.wins += 1.0

    @property
    def win_rate(self):
        return self.wins / self.visits if self.visits else 0.0

    def is_fully_expanded(self):
        return not self.untried_moves


class SearchResult:
    """Container for everything the agent has to report about one move."""

    __slots__ = ("move", "row", "col", "win_probability", "simulations",
                 "nodes_expanded", "max_depth", "elapsed_ms", "strategy",
                 "root_visits")

    def __init__(self, move, row, col, win_probability, simulations,
                 nodes_expanded, max_depth, elapsed_ms, strategy, root_visits):
        self.move = move
        self.row = row
        self.col = col
        self.win_probability = win_probability
        self.simulations = simulations
        self.nodes_expanded = nodes_expanded
        self.max_depth = max_depth
        self.elapsed_ms = elapsed_ms
        self.strategy = strategy
        self.root_visits = root_visits


class MCTSAgent:
    """
    The Hex AI agent.

    `choose_move` returns the best legal move found inside the given time
    budget together with the statistics required by the output format.
    """

    def __init__(self, time_limit_ms=DEFAULT_TIME_LIMIT_MS,
                 exploration=EXPLORATION_CONSTANT, seed=None):
        if time_limit_ms <= 0:
            raise HexError("The time limit per move must be a positive number "
                           "of milliseconds (received: %r)." % (time_limit_ms,))
        self.time_limit = time_limit_ms / 1000.0
        self.exploration = exploration
        self.rng = random.Random(seed)

    # ------------------------------------------------------------------ public
    def choose_move(self, board, player):
        start = time.perf_counter()
        legal = board.legal_moves()
        if not legal:
            raise BoardFullError(
                "MCTS cannot search: the board is full and holds no legal move.")

        opponent = 3 - player

        # -- Tactical pre-filter (domain knowledge injected at the root) -------
        # (a) an immediate winning move is played at once - no search needed.
        for mv in legal:
            board.place(mv, player)
            won = board.is_connected(player)
            board.remove(mv)
            if won:
                r, c = board.coords(mv)
                return SearchResult(mv, r, c, 1.0, 0, 0, 0,
                                    (time.perf_counter() - start) * 1000.0,
                                    "MCTS(UCT) + immediate-win detection", 0)

        # (b) if the opponent can win next ply, only blocking moves are kept.
        blocking = []
        for mv in legal:
            board.place(mv, opponent)
            threat = board.is_connected(opponent)
            board.remove(mv)
            if threat:
                blocking.append(mv)
        root_moves = blocking if blocking else legal
        strategy = ("MCTS(UCT) + forced-block filter" if blocking
                    else "Monte Carlo Tree Search (UCT)")

        # -- Full MCTS --------------------------------------------------------
        self.rng.shuffle(root_moves)
        root = MCTSNode(None, None, opponent, list(root_moves))
        simulations = 0
        nodes_expanded = 0
        max_depth = 0
        deadline = start + self.time_limit

        while time.perf_counter() < deadline:
            node = root
            state = board.copy()
            to_move = player
            depth = 0

            # 1. SELECTION -----------------------------------------------------
            while node.is_fully_expanded() and node.children \
                    and node.terminal_winner == EMPTY:
                node = node.uct_select_child(self.exploration)
                state.place(node.move, to_move)
                to_move = 3 - to_move
                depth += 1

            # 2. EXPANSION -----------------------------------------------------
            if node.terminal_winner == EMPTY:
                if node.untried_moves is None:
                    node.untried_moves = state.legal_moves()
                    self.rng.shuffle(node.untried_moves)
                if node.untried_moves:
                    mv = node.untried_moves.pop()
                    state.place(mv, to_move)
                    node = node.expand(mv, to_move)
                    nodes_expanded += 1
                    to_move = 3 - to_move
                    depth += 1
                    if state.is_connected(node.player_just_moved):
                        node.terminal_winner = node.player_just_moved

            if depth > max_depth:
                max_depth = depth

            # 3. SIMULATION (rollout) -----------------------------------------
            if node.terminal_winner != EMPTY:
                winner = node.terminal_winner
            else:
                winner = self._rollout(state, to_move)
            simulations += 1

            # 4. BACKPROPAGATION ----------------------------------------------
            while node is not None:
                node.update(winner)
                node = node.parent

        elapsed_ms = (time.perf_counter() - start) * 1000.0

        # -- Final move choice: the most visited (most robust) child -----------
        if not root.children:
            # Degenerate case (absurdly small time budget): fall back to a
            # random legal move so that the game can always continue.
            mv = self.rng.choice(root_moves)
            r, c = board.coords(mv)
            return SearchResult(mv, r, c, 0.0, simulations, nodes_expanded,
                                max_depth, elapsed_ms,
                                strategy + " [time budget exhausted]", root.visits)

        best = max(root.children, key=lambda ch: (ch.visits, ch.win_rate))
        r, c = board.coords(best.move)
        return SearchResult(best.move, r, c, best.win_rate, simulations,
                            nodes_expanded, max_depth, elapsed_ms, strategy,
                            root.visits)

    # ----------------------------------------------------------------- private
    def _rollout(self, state, to_move):
        """
        Uniformly random play-out.

        Because Hex can never end in a draw, a *completely filled* board always
        contains exactly one winner.  The remaining empty cells can therefore
        be shuffled once and dealt alternately to both players; the resulting
        final position is statistically identical to playing random moves one
        by one, but it removes all per-move bookkeeping and makes the rollout
        an O(N^2) operation.
        """
        cells = state.cells
        empties = [i for i, v in enumerate(cells) if v == EMPTY]
        if not empties:
            return state.winner()
        self.rng.shuffle(empties)
        board_copy = cells[:]
        player = to_move
        for i in empties:
            board_copy[i] = player
            player = 3 - player
        return PLAYER_A if player_a_wins_on_full_board(
            board_copy, state.size, state.neighbours) else PLAYER_B


# ============================================================================
# 3. INPUT / OUTPUT HELPERS
# ============================================================================
class OutputLogger:
    """Writes every line simultaneously to the console and to outputPS04.txt."""

    def __init__(self, path, mode="w"):
        self.path = path
        try:
            self.handle = open(path, mode, encoding="utf-8")
        except OSError as exc:
            raise HexError("Cannot open output file '%s' : %s" % (path, exc))

    def write(self, text=""):
        print(text)
        self.handle.write(text + "\n")
        self.handle.flush()

    def write_prompt(self, text):
        """Show a prompt on the console and mirror it into the output file."""
        self.handle.write(text + "\n")
        self.handle.flush()

    def close(self):
        try:
            self.handle.close()
        except OSError:
            pass


def format_int(value):
    return "{:,}".format(int(value))


def parse_move(text, size):
    """
    Convert a user string such as '4,1' / '4 1' / '(4, 1)' into (row, col).
    Raises InvalidMoveError with a descriptive message for every bad input.
    """
    if text is None:
        raise InvalidMoveError("No input received.")
    tokens = [t for t in re.split(r"[\s,;()\[\]]+", text.strip()) if t]
    if len(tokens) != 2:
        raise InvalidMoveError(
            "Expected exactly two numbers in the form 'row,col' "
            "(received: '%s')." % text.strip())
    try:
        row, col = int(tokens[0]), int(tokens[1])
    except ValueError:
        raise InvalidMoveError(
            "Row and column must be integers (received: '%s')." % text.strip())
    if not (0 <= row < size and 0 <= col < size):
        raise InvalidMoveError(
            "Move (%d,%d) is out of range - valid rows/cols are 0..%d."
            % (row, col, size - 1))
    return row, col


def load_game_input(path):
    """
    Read inputPS04.txt and return (size, time_limit_ms, cells).

    Format :  line 1  -> N
              line 2  -> time limit in milliseconds
              line 3+ -> the N x N matrix (blank lines and '#' comments ignored)
    An absent matrix is treated as an empty board.
    """
    if not os.path.isfile(path):
        raise InvalidBoardError("Input file '%s' was not found." % path)
    try:
        with open(path, "r", encoding="utf-8") as fh:
            raw = fh.read()
    except OSError as exc:
        raise InvalidBoardError("Cannot read input file '%s' : %s" % (path, exc))

    lines = [ln.strip() for ln in raw.splitlines()]
    lines = [ln for ln in lines if ln and not ln.startswith("#")]
    if len(lines) < 2:
        raise InvalidBoardError(
            "Input file '%s' must contain at least the board size and the "
            "time limit." % path)

    header = []
    for ln in lines[:2]:
        header.extend(t for t in re.split(r"[\s,]+", ln) if t)
    if len(header) != 2:
        raise InvalidBoardError(
            "The first two input lines must contain only the board size and "
            "the time limit.")

    try:
        size = int(header[0])
    except ValueError:
        raise InvalidBoardError("Board size '%s' is not an integer." % header[0])
    if not MIN_BOARD_SIZE <= size <= MAX_BOARD_SIZE:
        raise InvalidBoardError(
            "Board size must satisfy %d <= N <= %d (received: %d)."
            % (MIN_BOARD_SIZE, MAX_BOARD_SIZE, size))

    try:
        time_limit = int(float(header[1]))
    except (ValueError, OverflowError):
        raise InvalidBoardError("Time limit '%s' is not a number." % header[1])
    if time_limit <= 0:
        raise InvalidBoardError(
            "The time limit must be a positive number of milliseconds "
            "(received: %d)." % time_limit)

    body = []
    for ln in lines[2:]:
        row_tokens = [t for t in re.split(r"[\s,]+", ln) if t]
        if len(row_tokens) == 1 and len(row_tokens[0]) == size:
            row_tokens = list(row_tokens[0])
        body.extend(row_tokens)
    expected = size * size
    if not body:
        cells = [EMPTY] * expected
    elif len(body) != expected:
        raise InvalidBoardError(
            "The board matrix holds %d values but %d were expected for a "
            "%dx%d board." % (len(body), expected, size, size))
    else:
        cells = []
        for tok in body:
            try:
                val = int(tok)
            except ValueError:
                raise InvalidBoardError(
                    "Board cell '%s' is not an integer - only 0, 1 and 2 are "
                    "allowed." % tok)
            if val not in (EMPTY, PLAYER_A, PLAYER_B):
                raise InvalidBoardError(
                    "Board cell value %d is invalid - only 0, 1 and 2 are "
                    "allowed." % val)
            cells.append(val)

    a_count, b_count = cells.count(PLAYER_A), cells.count(PLAYER_B)
    if a_count - b_count not in (0, 1):
        raise InvalidBoardError(
            "Inconsistent board: Player A owns %d cells and Player B owns %d. "
            "Player A moves first, so A must own either as many stones as B "
            "or exactly one more." % (a_count, b_count))
    return size, time_limit, cells


def prompt_for_setup():
    """Fallback used when the input file is missing or unusable."""
    size = None
    while size is None:
        try:
            raw = input("Enter board size N (%d-%d): "
                        % (MIN_BOARD_SIZE, MAX_BOARD_SIZE))
        except (EOFError, KeyboardInterrupt):
            raise HexError("No input available - the program will stop.")
        try:
            value = int(raw.strip())
        except ValueError:
            print("  ERROR : the board size must be an integer.")
            continue
        if not MIN_BOARD_SIZE <= value <= MAX_BOARD_SIZE:
            print("  ERROR : the board size must satisfy %d <= N <= %d."
                  % (MIN_BOARD_SIZE, MAX_BOARD_SIZE))
            continue
        size = value

    limit = None
    while limit is None:
        try:
            raw = input("Enter time limit per AI move in ms [%d]: "
                        % DEFAULT_TIME_LIMIT_MS)
        except (EOFError, KeyboardInterrupt):
            raise HexError("No input available - the program will stop.")
        raw = raw.strip()
        if not raw:
            limit = DEFAULT_TIME_LIMIT_MS
            continue
        try:
            value = int(float(raw))
        except (ValueError, OverflowError):
            print("  ERROR : the time limit must be a number.")
            continue
        if value <= 0:
            print("  ERROR : the time limit must be positive.")
            continue
        limit = value
    return size, limit, [EMPTY] * (size * size)


# ============================================================================
# 4. GAME CONTROLLER
# ============================================================================
class HexGame:
    """Drives the alternating turns, the logging and the end-of-game report."""

    MAX_INVALID_ATTEMPTS = 10

    def __init__(self, size, time_limit_ms, cells, logger, seed=None):
        self.board = HexBoard(size, cells)
        self.time_limit_ms = time_limit_ms
        self.logger = logger
        self.agent = MCTSAgent(time_limit_ms, seed=seed)
        self.turn = 0
        self.ai_moves = 0
        self.human_moves = 0
        self.ai_times = []
        self.ai_nodes = []
        self.ai_depths = []
        self.ai_sims = []
        self.aborted = False

    # ------------------------------------------------------------------ turns
    def current_player(self):
        """Player A always moves first, so the stone counts fix the turn."""
        return PLAYER_A if self.board.stone_count(PLAYER_A) == \
            self.board.stone_count(PLAYER_B) else PLAYER_B

    def run(self):
        self._log_header()
        winner = self.board.winner()
        if winner:
            self.logger.write("The supplied board is already a terminal state.")
            self._log_game_over(winner)
            return winner

        while True:
            if self.board.is_full():
                break
            self.turn += 1
            player = self.current_player()
            if player == PLAYER_A:
                winner = self._ai_turn()
            else:
                winner = self._human_turn()
                if self.aborted:
                    self._log_game_over(EMPTY)
                    return EMPTY
            if winner:
                self._log_game_over(winner)
                return winner

        winner = self.board.winner()
        self._log_game_over(winner)
        return winner

    def _ai_turn(self):
        result = self.agent.choose_move(self.board, PLAYER_A)
        self.board.place(result.move, PLAYER_A)
        winner = self.board.winner()

        self.ai_moves += 1
        self.ai_times.append(result.elapsed_ms)
        self.ai_nodes.append(result.nodes_expanded)
        self.ai_depths.append(result.max_depth)
        self.ai_sims.append(result.simulations)

        log = self.logger
        log.write("")
        log.write("=" * 20 + "Turn %d" % self.turn + "=" * 31)
        log.write("Player                    : A (AI)")
        log.write("Move Selected             : (%d,%d)" % (result.row, result.col))
        log.write("Search Algorithm          : %s" % result.strategy)
        log.write("Exploration Constant (c)  : %.3f" % self.agent.exploration)
        log.write("Simulations (Rollouts)    : %s" % format_int(result.simulations))
        log.write("Nodes Expanded            : %s" % format_int(result.nodes_expanded))
        log.write("Search Depth (tree)       : %d" % result.max_depth)
        log.write("Heuristic Score (Win Prob): %s"
                  % ("+INF" if winner == PLAYER_A else "%.4f" % result.win_probability))
        log.write("Execution Time            : %d ms" % round(result.elapsed_ms))
        self._log_status(winner)
        return winner

    def _human_turn(self):
        log = self.logger
        size = self.board.size
        attempts = 0
        start = time.perf_counter()
        row = col = idx = None

        log.write("")
        log.write("=" * 20 + "Turn %d" % self.turn + "=" * 31)
        log.write("Player                    : B (Human)")
        log.write("Current Board :")
        log.write(self.board.render())

        while idx is None:
            prompt = "Player B, Enter your move (row,col): "
            try:
                raw = input(prompt)
            except (EOFError, KeyboardInterrupt):
                log.write_prompt(prompt)
                log.write("")
                log.write("No further input available - the game is stopped.")
                self.aborted = True
                return EMPTY
            log.write_prompt(prompt + raw)
            try:
                row, col = parse_move(raw, size)
                idx = self.board.validate_move(row, col)
            except HexError as exc:
                attempts += 1
                log.write("Move Entered              : %s" % raw.strip())
                log.write("Move Validation           : INVALID - %s" % exc)
                if attempts >= self.MAX_INVALID_ATTEMPTS:
                    log.write("Too many invalid moves (%d) - the game is stopped."
                              % attempts)
                    self.aborted = True
                    return EMPTY
                log.write("Please try again.")
                idx = None

        self.board.place(idx, PLAYER_B)
        elapsed_ms = (time.perf_counter() - start) * 1000.0
        winner = self.board.winner()
        self.human_moves += 1

        log.write("Move Entered              : (%d,%d)" % (row, col))
        log.write("Move Validation           : VALID")
        log.write("Invalid Attempts          : %d" % attempts)
        log.write("Execution Time            : %d ms" % round(elapsed_ms))
        self._log_status(winner)
        return winner

    # ---------------------------------------------------------------- logging
    def _log_status(self, winner):
        log = self.logger
        if winner:
            log.write("Game Status               : TERMINAL")
            log.write("Terminal State            : YES")
            log.write("Winner                    : Player %s" % PLAYER_NAME[winner])
            path = self.board.winning_path(winner)
            log.write("Winning Path              : %s"
                      % " -> ".join("(%d,%d)" % rc for rc in path))
        elif self.board.is_full():
            log.write("Game Status               : TERMINAL (board full)")
        else:
            log.write("Game Status               : CONTINUE")
        log.write("Current Board :")
        log.write(self.board.render())

    def _log_header(self):
        log = self.logger
        log.write(SEPARATOR)
        log.write("           HEX GAME AI - MONTE CARLO TREE SEARCH (UCT) - GROUP G116")
        log.write(SEPARATOR)
        log.write("Board Size                : %d x %d" % (self.board.size, self.board.size))
        log.write("Time Limit per AI Move    : %d ms" % self.time_limit_ms)
        log.write("Player A (1)              : AI Agent - connects TOP row to BOTTOM row")
        log.write("Player B (2)              : Human    - connects LEFT col to RIGHT col")
        log.write("Adjacency                 : (r-1,c) (r+1,c) (r,c-1) (r,c+1) "
                  "(r-1,c+1) (r+1,c-1)")
        log.write("Initial Board :")
        log.write(self.board.render())

    def _log_game_over(self, winner):
        log = self.logger
        log.write("")
        log.write(SEPARATOR)
        log.write(" " * 30 + "GAME OVER")
        log.write(SEPARATOR)
        if winner:
            log.write("Winner                    : Player %s" % PLAYER_NAME[winner])
        elif self.aborted:
            log.write("Winner                    : NONE (game aborted by the user)")
        else:
            log.write("Winner                    : NONE")
        log.write("Total Turns               : %d" % self.turn)
        log.write("Total AI Moves            : %d" % self.ai_moves)
        log.write("Total Human Moves         : %d" % self.human_moves)
        if self.ai_moves:
            log.write("Average Simulations       : %s"
                      % format_int(sum(self.ai_sims) / self.ai_moves))
            log.write("Average Nodes Expanded    : %s"
                      % format_int(sum(self.ai_nodes) / self.ai_moves))
            log.write("Average Search Depth      : %.1f"
                      % (sum(self.ai_depths) / self.ai_moves))
            log.write("Average AI Move Time      : %s ms"
                      % format_int(sum(self.ai_times) / self.ai_moves))
            log.write("Maximum Search Depth      : %d" % max(self.ai_depths))
            log.write("Maximum Nodes Expanded    : %s" % format_int(max(self.ai_nodes)))
        if winner == PLAYER_A:
            result = "PLAYER_A_WINS"
        elif winner == PLAYER_B:
            result = "PLAYER_B_WINS"
        else:
            result = "GAME_ABORTED" if self.aborted else "NO_RESULT"
        log.write("Game Result               : %s" % result)
        log.write(SEPARATOR)


# ============================================================================
# 5. BUILT-IN TEST CASES  (run with:  python G116_A2_PS04.py --test)
# ============================================================================
def _tc_adjacency(log):
    """TEST CASE 1 - the six legal adjacencies / two forbidden diagonals."""
    board = HexBoard(7)
    nb = set(board.neighbours_of(3, 3))
    expected = {(2, 3), (4, 3), (3, 2), (3, 4), (2, 4), (4, 2)}
    forbidden = {(2, 2), (4, 4)}
    assert nb == expected, "Neighbours of (3,3) are wrong: %s" % sorted(nb)
    assert not (nb & forbidden), "Forbidden diagonals were returned."
    corner = set(board.neighbours_of(0, 0))
    assert corner == {(0, 1), (1, 0)}, "Corner (0,0) adjacency is wrong: %s" % corner
    log.write("  neighbours(3,3) = %s" % sorted(nb))
    log.write("  forbidden (2,2) and (4,4) correctly absent; corner (0,0) = %s"
              % sorted(corner))
    return True


def _tc_winning_path_with_diagonal(log):
    """TEST CASE 2 - the 5x5 example of the problem statement (bottom-left win)."""
    grid = [[0, 0, 1, 0, 0],
            [0, 0, 1, 1, 0],
            [2, 2, 2, 1, 0],
            [0, 0, 2, 1, 0],
            [0, 0, 1, 2, 0]]
    board = HexBoard(5, [v for row in grid for v in row])
    assert board.winner() == PLAYER_A, "Player A should have won this position."
    path = board.winning_path(PLAYER_A)
    assert path[0][0] == 0 and path[-1][0] == 4, "Path must span top to bottom."
    assert (4, 2) in path, "The bottom-left diagonal cell (4,2) must be used."
    log.write("  winner = Player A")
    log.write("  winning path = %s" % " -> ".join("(%d,%d)" % rc for rc in path))
    return True


def _tc_player_b_win(log):
    """TEST CASE 3 - Player B connects the left column to the right column."""
    board = HexBoard(7)
    for c in range(7):
        board.place(board.index(3, c), PLAYER_B)
    assert board.is_connected(PLAYER_B), "Player B's horizontal chain is not detected."
    assert not board.is_connected(PLAYER_A), "Player A must not be connected."
    assert board.winner() == PLAYER_B
    log.write("  Player B row-3 chain detected, winner = Player B")
    return True


def _tc_agent_finds_winning_move(log):
    """TEST CASE 4 - the agent plays the single move that wins immediately."""
    board = HexBoard(7)
    for r in range(6):                       # A owns column 3 of rows 0..5
        board.place(board.index(r, 3), PLAYER_A)
    for r in range(5):                       # B has some stones elsewhere
        board.place(board.index(r, 5), PLAYER_B)
    agent = MCTSAgent(400, seed=7)
    result = agent.choose_move(board, PLAYER_A)
    assert (result.row, result.col) in ((6, 3), (6, 2)), \
        "Expected a winning move at (6,3) or (6,2), got (%d,%d)" \
        % (result.row, result.col)
    assert result.nodes_expanded == 0, \
        "Tactical scans must not be reported as expanded MCTS nodes."
    log.write("  agent move = (%d,%d) via '%s' | win probability = %.2f"
              % (result.row, result.col, result.strategy, result.win_probability))
    return True


def _tc_agent_legality_and_time(log):
    """TEST CASE 5 - the agent respects the time budget and returns a legal move."""
    board = HexBoard(9)
    board.place(board.index(4, 4), PLAYER_A)
    board.place(board.index(2, 2), PLAYER_B)
    agent = MCTSAgent(500, seed=11)
    started = time.perf_counter()
    result = agent.choose_move(board, PLAYER_A)
    elapsed = (time.perf_counter() - started) * 1000.0
    assert board.cells[result.move] == EMPTY, "The agent chose an occupied cell."
    assert elapsed < 1500, "The agent exceeded its time budget (%.0f ms)." % elapsed
    assert result.simulations > 0, "No rollout was executed."
    log.write("  move=(%d,%d) simulations=%s nodes=%s depth=%d time=%d ms"
              % (result.row, result.col, format_int(result.simulations),
                 format_int(result.nodes_expanded), result.max_depth,
                 round(result.elapsed_ms)))
    return True


def _tc_invalid_user_input(log):
    """TEST CASE 6 - malformed / illegal human input is rejected gracefully."""
    board = HexBoard(7)
    board.place(board.index(2, 2), PLAYER_A)
    bad_inputs = ["", "abc", "3", "1,2,3", "x,y", "9,9", "-1,4", "2,2"]
    for text in bad_inputs:
        try:
            r, c = parse_move(text, board.size)
            board.validate_move(r, c)
        except HexError as exc:
            log.write("  input %-8r rejected : %s" % (text, exc))
        else:
            raise AssertionError("Input %r should have been rejected." % text)
    r, c = parse_move(" (4, 1) ", board.size)
    assert (r, c) == (4, 1), "Valid input '(4, 1)' was parsed as (%d,%d)" % (r, c)
    log.write("  input '(4, 1)' accepted as (4,1)")
    return True


def _tc_board_edge_cases(log):
    """TEST CASE 7 - board/file edge cases: full board, duplicate move, bad file."""
    board = HexBoard(7)
    player = PLAYER_A
    for i in range(49):                      # fill the whole board
        board.place(i, player)
        player = 3 - player
    assert board.is_full() and not board.legal_moves()
    try:
        MCTSAgent(100, seed=3).choose_move(board, PLAYER_A)
    except BoardFullError as exc:
        log.write("  full board rejected : %s" % exc)
    else:
        raise AssertionError("A full board must raise BoardFullError.")
    try:
        board.place(0, PLAYER_B)
    except InvalidMoveError as exc:
        log.write("  duplicate insert rejected : %s" % exc)
    else:
        raise AssertionError("Placing on an occupied cell must raise.")
    small = HexBoard(7)
    try:
        small.remove(0)
    except InvalidMoveError as exc:
        log.write("  delete on empty cell rejected : %s" % exc)
    else:
        raise AssertionError("Removing an empty cell must raise.")
    tmp = "_tmp_bad_input_G116.txt"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write("5\n2000\n")                # 5 is outside 7..11
    try:
        load_game_input(tmp)
    except InvalidBoardError as exc:
        log.write("  bad input file rejected : %s" % exc)
    else:
        raise AssertionError("A board size of 5 must be rejected.")
    finally:
        os.remove(tmp)
    try:
        load_game_input("no_such_file_G116.txt")
    except InvalidBoardError as exc:
        log.write("  missing input file rejected : %s" % exc)
    non_finite = "_tmp_non_finite_time_G116.txt"
    with open(non_finite, "w", encoding="utf-8") as fh:
        fh.write("7\ninf\n")
    try:
        load_game_input(non_finite)
    except InvalidBoardError as exc:
        log.write("  non-finite time rejected : %s" % exc)
    else:
        raise AssertionError("A non-finite time limit must be rejected.")
    finally:
        os.remove(non_finite)
    compact = "_tmp_compact_input_G116.txt"
    with open(compact, "w", encoding="utf-8") as fh:
        fh.write("7\n2000\n" + "0000000\n" * 7)
    try:
        size, limit, cells = load_game_input(compact)
        assert size == 7 and limit == 2000 and cells == [EMPTY] * 49
        log.write("  compact board rows accepted : 7 rows of '0000000'")
    finally:
        os.remove(compact)
    return True


TEST_CASES = (
    ("TEST CASE 1 : Hex adjacency rules (6 neighbours, 2 forbidden diagonals)",
     _tc_adjacency),
    ("TEST CASE 2 : Terminal detection + winning path (problem-statement example)",
     _tc_winning_path_with_diagonal),
    ("TEST CASE 3 : Player B left-right connection detection",
     _tc_player_b_win),
    ("TEST CASE 4 : MCTS agent plays an immediate winning move",
     _tc_agent_finds_winning_move),
    ("TEST CASE 5 : MCTS agent legality, statistics and time budget",
     _tc_agent_legality_and_time),
    ("TEST CASE 6 : Invalid / malformed human input handling",
     _tc_invalid_user_input),
    ("TEST CASE 7 : Data-structure and input-file edge cases",
     _tc_board_edge_cases),
)


def run_test_cases(logger):
    logger.write("")
    logger.write(SEPARATOR)
    logger.write(" " * 26 + "BUILT-IN TEST CASES")
    logger.write(SEPARATOR)
    passed = 0
    for title, func in TEST_CASES:
        logger.write("")
        logger.write(title)
        try:
            func(logger)
        except AssertionError as exc:
            logger.write("  RESULT : FAILED - %s" % exc)
        except HexError as exc:
            logger.write("  RESULT : FAILED - unexpected error : %s" % exc)
        else:
            passed += 1
            logger.write("  RESULT : PASSED")
    logger.write("")
    logger.write("%d of %d test cases passed." % (passed, len(TEST_CASES)))
    logger.write(SEPARATOR)
    return passed == len(TEST_CASES)


# ============================================================================
# 6. ENTRY POINT
# ============================================================================
def build_arg_parser():
    parser = argparse.ArgumentParser(
        description="Hex game AI (Monte Carlo Tree Search / UCT) - Group G116")
    parser.add_argument("--input", default=DEFAULT_INPUT_FILE,
                        help="input file (default: %s)" % DEFAULT_INPUT_FILE)
    parser.add_argument("--output", default=DEFAULT_OUTPUT_FILE,
                        help="output file (default: %s)" % DEFAULT_OUTPUT_FILE)
    parser.add_argument("--test", action="store_true",
                        help="run the built-in test cases instead of a game")
    parser.add_argument("--append", action="store_true",
                        help="append to the output file instead of overwriting")
    parser.add_argument("--seed", type=int, default=None,
                        help="seed of the rollout RNG (reproducible games)")
    return parser


def main(argv=None):
    args = build_arg_parser().parse_args(argv)
    logger = None
    try:
        logger = OutputLogger(args.output, "a" if args.append else "w")
        if args.test:
            return 0 if run_test_cases(logger) else 1

        try:
            size, time_limit, cells = load_game_input(args.input)
            logger.write("Input file read successfully : %s" % args.input)
        except InvalidBoardError as exc:
            logger.write("INPUT ERROR : %s" % exc)
            logger.write("Falling back to manual setup.")
            size, time_limit, cells = prompt_for_setup()

        game = HexGame(size, time_limit, cells, logger, seed=args.seed)
        game.run()
        logger.write("")
        logger.write("Complete transcript written to '%s'." % args.output)
        return 0
    except KeyboardInterrupt:
        if logger:
            logger.write("")
            logger.write("Interrupted by the user - the program stops cleanly.")
        return 1
    except HexError as exc:
        message = "FATAL ERROR : %s" % exc
        if logger:
            logger.write(message)
        else:
            print(message, file=sys.stderr)
        return 1
    finally:
        if logger:
            logger.close()


if __name__ == "__main__":
    sys.exit(main())
